Script started on Fri 29 May 2015 10:51:05 PM PDT
~
mchen046@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * checksyscalls.sh      is your cpp file doing proper error checking?     |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mmchen046[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd CS100/rshell
[s%%%%%%%%%%[u[0;32mmchen046[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (signals) [0;36m$[0m make
if [ ! -d bin ]; then mkdir bin; fi
g++ -std=c++11 -Wall -Werror -pedantic ./src/rshell.cpp -o bin/rshell
g++ -std=c++11 -Wall -Werror -pedantic ./src/cp.cpp -o bin/cp
g++ -std=c++11 -Wall -Werror -pedantic ./src/ls.cpp -o bin/ls
g++ -std=c++11 -Wall -Werror -pedantic ./src/mv.cpp -o bin/mv
g++ -std=c++11 -Wall -Werror -pedantic ./src/rm.cpp -o bin/rm
[s%%%%%%%%%%[u[0;32mmchen046[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (signals) [0;36m$[0m bin/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd CS  -
/home/csmajs/mchen046/CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd -
/home/csmajs/mchen046
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd -
/home/csmajs/mchen046/CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd -
/home/csmajs/mchen046
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd -
/home/csmajs/mchen046/CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m#tilde
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd ~
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd -
/home/csmajs/mchen046/CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd CS100/rshell               cd -
/home/csmajs/mchen046
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd ~/CS100/
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100[36m $ [0m#connectors          ignores whitespace
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100[36m $ [0mcd -                  -
/home/csmajs/mchen046/CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd            ~
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd     CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m#connectors
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd ~ && cd CS100/rshell
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcd    cd badDir || cd ~
chdir: No such file or directory
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~[36m $ [0mcd badDir || cd badDir || cd ~ && cd CS100/rshell
chdir: No such file or directory
chdir: No such file or directory
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m#cat
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcat > eif
hello world
this will be written to this test file
^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcat eif
hello world
this will be written to this test file
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mls
bin  eif  LICENSE  Makefile  README.md	src  tests
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mps
  PID TTY          TIME CMD
44207 pts/66   00:00:00 bash
44272 pts/66   00:00:00 rshell
45105 pts/66   00:00:00 ps
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m#sort
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0msort > eif
hello world
this will not be written to the f test file
^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcat eif
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mls
bin  eif  LICENSE  Makefile  README.md	src  tests
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mps
  PID TTY          TIME CMD
44207 pts/66   00:00:00 bash
44272 pts/66   00:00:00 rshell
45382 pts/66   00:00:00 ps
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mcat
hello
hello
world
world
cat
cat
prints
prints
twice!
twice!
^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0msort
hello
world
sort
prints
once
^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mls
bin  eif  LICENSE  Makefile  README.md	src  tests
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mps
  PID TTY          TIME CMD
44207 pts/66   00:00:00 bash
44272 pts/66   00:00:00 rshell
45784 pts/66   00:00:00 ps
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0m^C
[32mmchen046[36m@[32mhammer.cs.ucr.edu[36m:[32m~/CS100/rshell[36m $ [0mexit
[s%%%%%%%%%%[u[0;32mmchen046[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (signals) [0;36m$[0m exit
exit
~
mchen046@hammer $ exit
exit

Script done on Fri 29 May 2015 10:55:56 PM PDT
